### ISSUE TITLE
Wansview Q5 

### ISSUE THREAD

**Issue by peledzius** [R1N4x/Wansview_Root#1]
Nice! It actually worked for Wansview Q5 cloud camera with **07.26000.07.12** firmware. I used instructions for [07.26100.07.12 firmware](https://github.com/R1N4x/Wansview_Root/tree/main/FW%2007.26100.07.12).

Now I'm trying to find a way to disable camera manually, so I could turn on/off camera on demand. Whenever I kill `/mnt/mtd/app/initApp` process, camera restarts after minute automatically, I don't know why it does behave like that.

**Comment by R1N4x** [comment]
Hmm as far as I remember my W6 did not restart itself. 

Have you tried to kill the webserver too? Maybe there is a kind of watchdog somewhere.

**Comment by peledzius** [comment]
> Maybe there is a kind of watchdog somewhere.

Yeah, there was. You need to pass magic character to watchdog after you kill process, so it wouldn't cause a reboot:

 `echo 'V' > /dev/watchdog`

Did you try adjusting IR-cut sensitivity? Looks like it doesn't do anything for my cam when I change the value. My camera switches to night vision when it's not so dark, so I just trying different `ircut` and `infrared` config options to see if I can adjust this behaviour.
